### ISSUE TITLE
Reset test data script does not reset next order id

### ISSUE THREAD

**Issue by stenza** [ccondrup/mage-reset#2]
I think it would be great to reset the last order id in table _eav_entity_store_ for numbering starts from the front again.

```sql
UPDATE
	'eav_entity_store'
SET
	'increment_last_id' = '100000000';

**Comment by ccondrup** [comment]
Thank you for your suggestion. I agree with you but I found that it is a bit more complex; You have to reset the value per store, and there are several connected values to reset. For these reasons, resetting the IDs was split into a separate file:
https://github.com/ccondrup/mage-reset/blob/master/reset_increment_ids.sql

Take a look at the comments in the first lines of reset_increment_ids.sql:
You define which ID you want to the next one to be for the given store and run that script to set all the IDs for the correct store.

If I misunderstood you, please clarify :)

**Comment by stenza** [comment]
My bad, I was distrait.
