### ISSUE TITLE
Reset increment ids suggestion

### ISSUE THREAD

**Issue by stenza** [ccondrup/mage-reset#3]
If you wish your numbering to look something like 201500001 where 2015 is the prefix, and 00001 is the running sequence, you should do the following:
```sql
SET @id_store   := '1';      -- The id of the Mage store you wish to change. Run this script for each store.
SET @id_prefix  := 2015;     -- Prefix for new numbers, alphanumeric is OK, NULL or numeric preferrable
SET @nr_nextid  := '00001';    -- Next order id. Match padlength! Mage default 00000001 = 8 digits, means @nr_padding should be 8.
SET @nr_padding := 5;        -- How many digits did you set in nr_nextid? Mage default 8
```

But you can't. In line 44 CONCAT do the best, but in line 32 the 3rd parameters is an integer.
So 00001 will be 1, and CONCAT(1, 1) set the increment_last_id to 11.

The example script work fine because its nextid = 10101.

I think line 32 should look like this:
```sql
CREATE PROCEDURE ccdata_set_defaults (IN id_store INT(5), IN id_prefix VARCHAR(15), IN nr_nextid VARCHAR(15))
```

**Comment by ccondrup** [comment]
@stenza Thanks, good catch! Try the updated version and report back if any issues remain :)
